/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_WriteFrameResume_H
#define ZSTDGPU_SRT_GENERATED_WriteFrameResume_H

#ifdef __hlsl_dx_compiler

ZSTDGPU_RW_BUFFER(uint32_t)         ZstdInOutFrameResumeState       : register(u0);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInBlockSizePrefix           : register(t0);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInPerFrameBlockCountAll     : register(t1);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInPerFrameSeqStreamMinIdx   : register(t2);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInPerFrameSeqStreamMaxIdx   : register(t3);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInPerSeqStreamFinalOffset1  : register(t4);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInPerSeqStreamFinalOffset2  : register(t5);
ZSTDGPU_RO_BUFFER(uint32_t)         ZstdInPerSeqStreamFinalOffset3  : register(t6);
ZSTDGPU_RO_BUFFER(zstdgpu_Counters) ZstdInCounters                  : register(t7);

typedef struct zstdgpu_WriteFrameResume_Consts
{
    uint32_t    frameCount;
} zstdgpu_WriteFrameResume_Consts;

ConstantBuffer<zstdgpu_WriteFrameResume_Consts> ZstdConstants_WriteFrameResume : register(b0);

#define ZSTDGPU_SRT_RS_WriteFrameResume "UAV(u0)" ", SRV(t0)" ", SRV(t1)" ", SRV(t2)" ", SRV(t3)" ", SRV(t4)" ", SRV(t5)" ", SRV(t6)" ", SRV(t7)" ", RootConstants(b0, num32BitConstants=1)"

static void zstdgpu_Srt_Fill(ZSTDGPU_PARAM_INOUT(zstdgpu_WriteFrameResume_SRT) srt)
{
    srt.inoutFrameResumeState       = ZstdInOutFrameResumeState;
    srt.inBlockSizePrefix           = ZstdInBlockSizePrefix;
    srt.inPerFrameBlockCountAll     = ZstdInPerFrameBlockCountAll;
    srt.inPerFrameSeqStreamMinIdx   = ZstdInPerFrameSeqStreamMinIdx;
    srt.inPerFrameSeqStreamMaxIdx   = ZstdInPerFrameSeqStreamMaxIdx;
    srt.inPerSeqStreamFinalOffset1  = ZstdInPerSeqStreamFinalOffset1;
    srt.inPerSeqStreamFinalOffset2  = ZstdInPerSeqStreamFinalOffset2;
    srt.inPerSeqStreamFinalOffset3  = ZstdInPerSeqStreamFinalOffset3;
    srt.inCounters                  = ZstdInCounters;
    srt.frameCount                  = ZstdConstants_WriteFrameResume.frameCount;
}

#else

static void zstdgpu_Srt_Fill(zstdgpu_WriteFrameResume_SRT &srt, const zstdgpu_ResourceDataCpu &cpuRes,
                             uint32_t     frameCount)
{
    srt.inoutFrameResumeState       = cpuRes.FrameResumeState;
    srt.inBlockSizePrefix           = cpuRes.BlockSizePrefix;
    srt.inPerFrameBlockCountAll     = cpuRes.PerFrameBlockCountAll;
    srt.inPerFrameSeqStreamMinIdx   = cpuRes.PerFrameSeqStreamMinIdx;
    srt.inPerFrameSeqStreamMaxIdx   = cpuRes.PerFrameSeqStreamMaxIdx;
    srt.inPerSeqStreamFinalOffset1  = cpuRes.PerSeqStreamFinalOffset1;
    srt.inPerSeqStreamFinalOffset2  = cpuRes.PerSeqStreamFinalOffset2;
    srt.inPerSeqStreamFinalOffset3  = cpuRes.PerSeqStreamFinalOffset3;
    srt.inCounters                  = cpuRes.Counters;
    srt.frameCount                  = frameCount;
}

#endif

#endif /* ZSTDGPU_SRT_GENERATED_WriteFrameResume_H */
